### ISSUE TITLE
.HTML to .XBEL Converter? Brave Bookmarks

### ISSUE THREAD

**Issue by emaginsf** [mddevils/floccus-bookmarks-to-markdown#1]
How to get Brave bookmark export (html) into XBEL
Could not find online converters.

**Comment by emaginsf** [comment]
Answer: Use Floccus Bookmark addon in your browser! Duh
Maybe add to readme

**Comment by elvisisvan** [comment]
> Answer: Use Floccus Bookmark addon in your browser! Duh Maybe add to readme

but can you view .html in obsidian?

![image](https://github.com/user-attachments/assets/33239767-2dd9-43a9-a4f0-f0e2f7480b00)

![image](https://github.com/user-attachments/assets/dfbd4a2c-c952-46e5-8fbd-9b154bb90504)

i tried using this plugin but i cannot get it to work, it doesn'n convert .xbel file to .md , how do you do this?
