### ISSUE TITLE
how do you fill the "xbel absolute folder path" and "markdown vault folder path" boxes?

### ISSUE THREAD

**Issue by elvisisvan** [mddevils/floccus-bookmarks-to-markdown#2]
i tried using this plugin but i cannot get it to work, it doesn't convert .xbel file to .md , how do you do this?

![xbel](https://github.com/user-attachments/assets/33239767-2dd9-43a9-a4f0-f0e2f7480b00)

![options](https://github.com/user-attachments/assets/dfbd4a2c-c952-46e5-8fbd-9b154bb90504)

**Comment by mddevils** [comment]
Xbel absolute folder path is the OS folder where the floccus xbel is located
ex: d:\floccus\

Markdown vault folder path is a path  relative to your Obisidian Vault folder (not OS)
ex: bookmarks


![j7fR9Il 1](https://github.com/user-attachments/assets/83bfa540-55aa-47e7-9fd2-4d4932e1098a)

![2P0YmwR 1](https://github.com/user-attachments/assets/90ffbaf2-ce0d-41ba-84cb-b30bb6624a1e)

**Comment by elvisisvan** [comment]
> Xbel absolute folder path is the OS folder where the floccus xbel is located ex: d:\floccus\
> 
> Markdown vault folder path is a path relative to your Obisidian Vault folder (not OS) ex: bookmarks

thanks for clarifying this, can you make both the paths consistent with each other by either setting both as absolute folder path to system or relative path to obsidian? or maybe add a toggle to choose between the 2 options?
